# Generated by Django 4.2 on 2024-12-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idVentas', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('idEmpleado', models.CharField(max_length=6)),
                ('idCliente', models.CharField(max_length=6)),
                ('idProductos', models.CharField(max_length=6)),
                ('idSucursal', models.CharField(max_length=6)),
                ('fecha_venta', models.CharField(max_length=6)),
                ('cantidad', models.CharField(max_length=6)),
                ('total', models.CharField(max_length=6)),
            ],
        ),
    ]
