# Generated by Django 4.2 on 2024-11-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('Fecha_nac', models.DateField()),
                ('sexo', models.CharField(max_length=100)),
                ('no_telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
