# Generated by Django 4.2 on 2024-12-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursales',
            old_name='idSucursal',
            new_name='idSucursales',
        ),
    ]
