# Generated by Django 5.1 on 2024-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idEmpleado', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('Fecha_nac', models.DateField()),
                ('sexo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('no_telefono', models.IntegerField()),
                ('puesto', models.CharField(max_length=100)),
            ],
        ),
    ]
