# Generated by Django 4.2 on 2024-12-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idProveedor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('curp', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('no_telefono', models.IntegerField()),
            ],
        ),
    ]
